name: tests
on: push
jobs:
  run_tests:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v3  # 更新为最新版本
        with:
          path: D:/Study/apache-maven-3.9.6/mvn_repo
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml